import React, { useState, useMemo } from "react";
import {
  X,
  Download,
  FileText,
  Calendar,
  MapPin,
  User,
  Shield,
  AlertTriangle,
} from "lucide-react";
import jsPDF from "jspdf";

interface Detection {
  id: string;
  class: string;
  confidence: number;
  bbox: [number, number, number, number];
  description: string;
  forensicSignificance: string;
}

interface AnalysisResult {
  detections: Detection[];
  imageUrl: string;
  timestamp: string;
  metadata: {
    resolution: string;
    fileSize: string;
    format: string;
  };
}

interface ForensicReportProps {
  result: AnalysisResult;
  onClose: () => void;
}

const ForensicReport: React.FC<ForensicReportProps> = ({
  result,
  onClose,
}) => {
  const caseNumber = `CASE-${Date.now().toString().slice(-8)}`;
  const reportDate = new Date().toLocaleDateString();
  const analysisTime = new Date(result.timestamp).toLocaleString();

  const [isGeneratingPDF, setIsGeneratingPDF] = useState(false);
  const [crimeSceneLocation, setCrimeSceneLocation] = useState("");
  const [investigatorName, setInvestigatorName] = useState("");
  const [showInputs, setShowInputs] = useState(false);

  const criticalEvidence = useMemo(() => {
    return result.detections.filter(
      (d) =>
        d.confidence > 0.9 &&
        ["knife", "gun", "weapon", "pistol", "rifle"].includes(
          d.class.toLowerCase()
        )
    );
  }, [result.detections]);

  const downloadPDF = async () => {
    if (!crimeSceneLocation.trim() || !investigatorName.trim()) {
      setShowInputs(true);
      return;
    }

    setIsGeneratingPDF(true);

    try {
      const pdf = new jsPDF("p", "mm", "a4");

      const pageWidth = pdf.internal.pageSize.getWidth();
      const pageHeight = pdf.internal.pageSize.getHeight();

      const margin = 15;
      let yPosition = margin;

      const now = new Date();

      const addWatermark = () => {
        pdf.setTextColor(240, 240, 240);
        pdf.setFont("helvetica", "bold");
        pdf.setFontSize(40);

        pdf.text("TEAM INVESTIGATOR", pageWidth / 2, pageHeight / 2, {
          align: "center",
          angle: 45,
        });

        pdf.setTextColor(0, 0, 0);
      };

      const checkNewPage = (height: number) => {
        if (yPosition + height > pageHeight - margin) {
          pdf.addPage();
          addWatermark();
          yPosition = margin;
        }
      };

      const addBoxSection = (title: string, content: string[]) => {
        const lineHeight = 6;
        const boxHeight = content.length * lineHeight + 20;

        checkNewPage(boxHeight);

        pdf.setFillColor(245, 248, 252);
        pdf.rect(
          margin,
          yPosition,
          pageWidth - margin * 2,
          boxHeight,
          "F"
        );

        pdf.setDrawColor(0, 100, 200);
        pdf.rect(
          margin,
          yPosition,
          pageWidth - margin * 2,
          boxHeight
        );

        let textY = yPosition + 8;

        pdf.setFont("helvetica", "bold");
        pdf.setFontSize(12);
        pdf.setTextColor(0, 102, 204);
        pdf.text(title, margin + 4, textY);

        textY += 8;

        pdf.setFont("helvetica", "normal");
        pdf.setFontSize(10);
        pdf.setTextColor(0, 0, 0);

        content.forEach((line) => {
          pdf.text(line, margin + 4, textY);
          textY += lineHeight;
        });

        yPosition += boxHeight + 10;
      };

      const addEvidenceTable = (detections: Detection[]) => {
        const rowHeight = 6;

        checkNewPage(20);

        pdf.setFont("helvetica", "bold");
        pdf.setFontSize(12);
        pdf.text("DETAILED EVIDENCE CATALOG", margin, yPosition);

        yPosition += 10;

        detections.forEach((d, index) => {
          checkNewPage(12);

          pdf.setFontSize(9);

          pdf.text(`${d.id}`, margin, yPosition);
          pdf.text(
            d.class.toUpperCase(),
            margin + 25,
            yPosition
          );
          pdf.text(
            `${Math.round(d.confidence * 100)}%`,
            margin + 80,
            yPosition
          );

          pdf.text(
            `[${d.bbox.join(",")}]`,
            margin + 110,
            yPosition
          );

          yPosition += rowHeight;
        });

        yPosition += 6;
      };

      // HEADER
      pdf.setFillColor(0, 100, 200);
      pdf.rect(0, 0, pageWidth, 35, "F");

      pdf.setTextColor(255, 255, 255);
      pdf.setFontSize(18);
      pdf.setFont("helvetica", "bold");

      pdf.text("FORENSIC ANALYSIS REPORT", pageWidth / 2, 18, {
        align: "center",
      });

      pdf.setFontSize(10);
      pdf.text(
        "Generated by ForensicAI Analyzer v2.1",
        pageWidth / 2,
        26,
        { align: "center" }
      );

      addWatermark();
      yPosition = 50;

      // CASE INFO
      addBoxSection("CASE INFORMATION", [
        `Case Number: ${caseNumber}`,
        `Date: ${reportDate}`,
        `Location: ${crimeSceneLocation}`,
        `Investigator: ${investigatorName}`,
        `Analysis Time: ${analysisTime}`,
      ]);

      // SUMMARY SAFE
      const total = result.detections.length;

      const avgConfidence =
        total > 0
          ? Math.round(
              (result.detections.reduce(
                (a, b) => a + b.confidence,
                0
              ) /
                total) *
                100
            )
          : 0;

      addBoxSection("SUMMARY", [
        `Total Evidence: ${total}`,
        `Critical Evidence: ${criticalEvidence.length}`,
        `Avg Confidence: ${avgConfidence}%`,
      ]);

      // TABLE
      addEvidenceTable(result.detections);

      // DISCLAIMER
      addBoxSection("DISCLAIMER", [
        "AI-generated preliminary analysis only",
        "Must be verified by forensic experts",
        "Not valid as sole legal evidence",
      ]);

      pdf.save(`Forensic_Report_${caseNumber}.pdf`);
    } catch (err) {
      console.error(err);
      alert("PDF generation failed");
    } finally {
      setIsGeneratingPDF(false);
      setShowInputs(false);
    }
  };

  return (
    <div className="fixed inset-0 bg-black/50 flex items-center justify-center p-4">
      <div className="bg-slate-900 rounded-2xl w-full max-w-4xl max-h-[90vh] overflow-hidden border border-blue-400/20">
        {/* HEADER */}
        <div className="flex justify-between p-6 border-b border-blue-400/20">
          <div>
            <h2 className="text-white text-xl font-bold">
              Forensic Report
            </h2>
            <p className="text-slate-400 text-sm">Case {caseNumber}</p>
          </div>

          <div className="flex gap-3">
            <button
              onClick={downloadPDF}
              className="bg-green-500 px-4 py-2 rounded-lg text-white"
            >
              <Download className="w-4 h-4 inline" /> Download
            </button>

            <button onClick={onClose}>
              <X className="text-white" />
            </button>
          </div>
        </div>

        {/* INPUT MODAL */}
        {showInputs && (
          <div className="absolute inset-0 bg-black/70 flex items-center justify-center">
            <div className="bg-slate-800 p-6 rounded-lg w-96">
              <input
                placeholder="Crime Scene Location"
                className="w-full mb-3 p-2"
                value={crimeSceneLocation}
                onChange={(e) =>
                  setCrimeSceneLocation(e.target.value)
                }
              />

              <input
                placeholder="Investigator Name"
                className="w-full mb-3 p-2"
                value={investigatorName}
                onChange={(e) =>
                  setInvestigatorName(e.target.value)
                }
              />

              <button
                onClick={downloadPDF}
                className="bg-green-500 w-full p-2"
              >
                Generate
              </button>
            </div>
          </div>
        )}

        {/* BODY (simplified view) */}
        <div className="p-6 text-white">
          <p>Total Evidence: {result.detections.length}</p>
          <p>
            Critical Evidence: {criticalEvidence.length}
          </p>
        </div>
      </div>
    </div>
  );
};

export default ForensicReport;